### ISSUE TITLE
Molfile paste does not work on Windows / Firefox

### ISSUE THREAD

**Issue by jliermann** [cheminfo/nmrium#1060] opened 2021-05-14 16:25 UTC
On Windows 10 / Firefox 81 (Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:81.0; WIA enabled) Gecko/20100101 Firefox/81.0), inserting a structure in MOL format by copy paste does not work. Saving the same file as .mol (see attachment) and dropping it works. Maybe a permissions issue?

[acetophenone.zip](https://github.com/cheminfo/nmrium/files/6479991/acetophenone.zip)

**Comment by lpatiny** [comment] 2021-05-14 18:03
@hamed-musallam Could you have a look to this. If we 'readText' is seems it should be supported by firefox: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

**Comment by lpatiny** [comment] 2021-05-15 07:40
Actually it is not a bug. This feature is not available on Firefox.

@hamed-musallam Please hide the 'paste' button if `navigator.clipboard.readText` is not present.

**Comment by jliermann** [comment] 2021-05-17 15:18
Thanks for the clarification. Another possibility would be to offer a text input for pasting if the browser does not have that feature.

**Comment by targos** [comment] 2021-05-17 16:18
Another possibility could be to listen to the "paste" event on the component and if the clipboard contains a molfile, add the molecule.

**Comment by hamed-musallam** [comment] 2021-05-25 13:16
@lpatiny 
Is there any way to trigger Paste manually instead of press on Ctrl +v?

**Comment by targos** [comment] 2021-05-25 13:32
@hamed-musallam 

In Firefox, you can do it with the browser's main menu:

![image](https://user-images.githubusercontent.com/2352663/119506624-6399ad00-bd6e-11eb-9929-911291d707c7.png)

**Comment by hamed-musallam** [comment] 2021-05-25 14:04
@targos 
I mean is there any way to trigger it programmatically? because as I know due to the browser security reasons we can not...

@lpatiny 
is it acceptable behavior to paste directly without press on paste molecule button from your point of view as an end-user?

**Comment by targos** [comment] 2021-05-25 14:07
There's no way to trigger it programmatically.

**Comment by hamed-musallam** [comment] 2021-05-31 07:52
@lpatiny 
what is your opinion?

**Comment by hamed-musallam** [comment] 2021-12-08 17:46
i will close it for now until we found a solution

**Closed by hamed-musallam** 2021-12-08 17:46 UTC
