### ISSUE TITLE
Fix SVG export to be compatible with word

### ISSUE THREAD

**Issue by jschneidewind** [cheminfo/nmrium#2166] opened 2023-02-20 11:31 UTC
# Current behaviour

Currently it is possible to export vector graphics of spectra as `.svg`. While this file format is well suited for many applications, there are some issues when using it with Microsoft Word, where it often does not render properly.

See for example (tested with Microsoft Word for Mac 2019):
[MLB-170-1_10_Word_SVG_import.pdf](https://github.com/cheminfo/nmrium/files/10783714/MLB-170-1_10_Word_SVG_import.pdf) (spectrum is only partially rendered and integral values are missing)

In contrast to how it should look like in the `.png`: 
![MLB-170-1_10](https://user-images.githubusercontent.com/41544471/220093022-8bb6afef-7a42-409a-887c-2022eec05cc2.png)

A work-around is to convert the `.svg` to `.pdf` using software such as Inkscape. In this conversion, however, some graphic elements are lost (e.g. the integral values). 
See for example: [MLB-170-1_10_Inkscape_SVG_to_PDF.pdf](https://github.com/cheminfo/nmrium/files/10783731/MLB-170-1_10_Inkscape_SVG_to_PDF.pdf)

Furthermore, when the color of the spectrum is changed within NMRium and it is then saved as `.svg`, the spectrum disappears in the `.svg` to `.pdf` conversion (see for example: [MLB-170-1_10_Color_Changed_Inkscape_SVG_to_PDF.pdf](https://github.com/cheminfo/nmrium/files/10783796/MLB-170-1_10_Color_Changed_Inkscape_SVG_to_PDF.pdf)). The spectrum is also not visible when the `.svg` is directly imported into Word.

# Suggested feature

If possible, it would be great if an option for the direct export to `.pdf` is added, which would expand the options for vector graphic export and enable direct use with Microsoft Word (which is of course commonly used for both teaching and publications).

Thanks for your work on NMRium!

For reference here are the original `.zip` Bruker file as well as the `.svg` files with original and changed color:

[MLB-170-1.zip](https://github.com/cheminfo/nmrium/files/10783857/MLB-170-1.zip)
![MLB-170-1_10](https://user-images.githubusercontent.com/41544471/220088946-bfb94765-00f9-48e6-a53b-19eee6abeeb4.svg)
![MLB-170-1_10_Color_Changed](https://user-images.githubusercontent.com/41544471/220092284-d9d11b60-ca5d-4276-8a27-b481bec107e3.svg)

**Comment by lpatiny** [comment] 2023-02-22 17:57
While PDF exportation could be possible it would require a large library to be bundled with NMRium. https://www.npmjs.com/package/pdfkit could be one of them.

I would first focus on fixing the bugs / limitations in SVG exportation.

@hamed-musallam Could you check why we are loosing the integration ?

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1484241/220711653-7d588705-b058-4601-879e-a36d51a02c77.png">

When I open the SVG in Inkscape there is no integration. I guess we are using a feature that is too recent and unsupported (rgba ?). 

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1484241/220713372-48ac5626-815e-4d6b-9fc5-c51315ac7046.png">

Same is true for the change of color of spectra that is problematic. Before changing we have for color:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/1484241/220714216-f759abf4-9009-4025-aff8-5f789b5acb90.png">

After changing

<img width="439" alt="image" src="https://user-images.githubusercontent.com/1484241/220714356-f70fd472-28a7-4ebe-9de2-cafd328926d5.png">

The color has now alpha channel. 

This can be related to: https://stackoverflow.com/questions/6042550/svg-fill-color-transparency-alpha

**Comment by hamed-musallam** [comment] 2023-03-07 07:58
@jschneidewind 

can you test with the last version of NMRium on https://dev.nmrium.org/  and see if the export as SVG works well or not?

**Comment by hamed-musallam** [comment] 2023-03-08 08:35
@jschneidewind

Now the problem should be resolved after we remove the x-axis grid during the exportation, can you test from your end with the last version of NMRium  https://dev.nmrium.org/

**Comment by jschneidewind** [comment] 2023-03-08 16:54
Thanks for your reply @hamed-musallam !  I just tested it with the dev version but unfortunately the problem seems to persist (after changing the color of the spectrum and exporting the SVG file, the spectrum itself is not visible when opened with Inkscape or Word, all other elements like the axis, integrals, peak labels, are shown).

**Comment by lpatiny** [comment] 2023-03-14 06:06
@hamed-musallam The branch is now working correctly and I can open it in inkscape without problems.

There is however an issue if you import it in Microsoft word and print from word to PDF. I did a LOT of testing by simplifying the SVG in order to track down the bug. 

- seems to be related to style
- seems to be related to size (width / height of SVG)
- seems not related to the fact that we have decimals in the path
- if I remove points in the following SVG in the path of the spectrum (at the level of the noise) it works correctly.

Here are the 2 files. It seems that Microsoft word it simplifying the path if it is too long (at least in Microsoft on macintosh) and I could not find an option that would prevent this.

If anybody could test those 2 files on windows and tell if it works would be nice. 

[Archive.zip](https://github.com/cheminfo/nmrium/files/10964625/Archive.zip)


Not working:

![image](https://user-images.githubusercontent.com/1484241/224910534-7e827201-11e3-412b-9454-7ae02bbb78d4.png)

Working:

![image](https://user-images.githubusercontent.com/1484241/224910435-8428b096-98c2-48b6-bb40-654b6e7acac8.png)

**Comment by hamed-musallam** [comment] 2023-03-14 08:30
I test with a windows machine, and this is what I got once I export the spectra as SVG and from MS World (Microsoft® Word for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20186) 64-bit ) as PDF 

it works perfect

[spectra smaple.pdf](https://github.com/cheminfo/nmrium/files/10966167/spectra.smaple.pdf)

**Comment by targos** [comment] 2023-03-14 08:37
Here's an example with my version of Word (drag and drop both svgs, save as PDF with default options)

[test.pdf](https://github.com/cheminfo/nmrium/files/10966219/test.pdf)

**Comment by hamed-musallam** [comment] 2023-03-14 08:37
>If anybody could test those 2 files on windows and tell if it works would be nice.

> [Archive.zip](https://github.com/cheminfo/nmrium/files/10964625/Archive.zip)

[sample 2.pdf](https://github.com/cheminfo/nmrium/files/10966214/sample.2.pdf)

it seems the problem is how  the MS Word convert the PDF, it seems at the MS Word version that i use in my windows machine works without a problem

**Comment by lpatiny** [comment] 2023-03-14 11:59
Ok this confirms it is a word problem. On my mac version 16.70 (23021201) I get the following pdf.

[mac-16.70-23021201.pdf](https://github.com/cheminfo/nmrium/files/10967938/mac-16.70-23021201.pdf)

From the following word document.

[document.docx.zip](https://github.com/cheminfo/nmrium/files/10967945/document.docx.zip)

Hopefully this will be resolved in a future version.

**Comment by hamed-musallam** [comment] 2023-03-15 11:42
@jschneidewind

The problem is resolved right now, concerning the PDF exportation, it works perfectly on the last release of MS World and it seems it is a bug in a specific release of MS Word.

Please test with the last version of NMRium and inform us if you still face the same problem.

**Closed** 2023-03-15 19:00 UTC
