### ISSUE TITLE
Import NMReData not working

### ISSUE THREAD

**Issue by NRayya** [cheminfo/nmrium#1735] opened 2022-08-29 14:22 UTC
I have exported NMReData with NMRium (from a jdx file) and tried to open it again but it didn't work.

**Comment by targos** [comment] 2022-08-29 14:28
Thanks for the report. Confirmed the bug with the "Full cytisine" example: https://www.swisstransfer.com/d/805f32a5-5b8e-4b0e-b105-aae28a64cf6b

**Comment by targos** [comment] 2022-08-29 15:04
@lpatiny @jobo322 I don't know if the bug is in the creation of the nmredata file or in the parsing?

**Comment by jobo322** [comment] 2022-08-29 15:14
There was some changes that broke the nmredata exportation (we don't keep the original data anymore). I am working on nmredata to use filelist-utils instead of an jsZip instance to support the nmredata importation by the package nmr-load-save,.

 we could check how to fix the export to nmredata. I think we could generate champ files of each spectrum at the moment of witte the nmrRecord file. @targos @lpatiny what do you think?

**Comment by lpatiny** [comment] 2022-08-29 15:28
For now I think that we should disable NMReData exportation. We will see how to use of filelist helps in order to be able to export the original data and we should keep in mind that if possible we should track where is the original data.

**Comment by CS76** [comment] 2022-09-09 09:43
For testing please consider the this example as well
[ethylbenzol_100-41-4.zip](https://github.com/cheminfo/nmrium/files/9534297/ethylbenzol_100-41-4.zip)

**Comment by lpatiny** [comment] 2022-09-20 19:39
@jobo322 Is this example working in the next release of NMRium using filelist ? If yes you could close this isssue in the related PR.

**Comment by CS76** [comment] 2022-09-26 12:16
@hamed-musallam

**Comment by jobo322** [comment] 2022-09-26 19:06
@targos the SDF file looks like
```
> <NMREDATA_2D_1H_1J_1H>
Jcamp_Location=file:jcamp/2d/cosy.jdx\
CorType=cosy \
PulseProgram=cosygpqf \
Larmor=600.20\
> <NMREDATA_2D_1H_1J_1H>
Jcamp_Location=file:jcamp/2d/cosy.jdx\
CorType=cosy \
PulseProgram=cosygpqf \
Larmor=600.20\
> <NMREDATA_2D_13C_NJ_1H>
Jcamp_Location=file:jcamp/2d/hmbc.jdx\
CorType=hmbc \
PulseProgram=hmbcgplpndqf \
Larmor=600.20\

```

 I need to check if an empty line between tags (> <NMREDATA_...) is mandatory or not. The nmredata parser uses this empty line as a delimitation to group the tag data. So adding this empty line between nmredata tags. the file is correctly imported.

https://www.swisstransfer.com/d/e77a20b8-09c2-499f-8c07-d99b5c4832eb

**Comment by lpatiny** [comment] 2022-09-26 19:10
@jobo322 Ok thanks. You are right that between tags we need an empty line. Does this mean that there could be a bug in the nmredata file saver ?

Anyway we will have to check how to be able to generate again nmredata now that we are using nmr-load-save. This is related to https://github.com/cheminfo/nmrium/issues/1774

**Comment by lpatiny** [comment] 2022-12-01 16:02
We close this issue because the file is corrupted.

**Closed by lpatiny** 2022-12-01 16:02 UTC
Labels: bug
