### ISSUE TITLE
Problem loading sample names from Bruker ZIP files

### ISSUE THREAD

**Issue by jschneidewind** [cheminfo/nmrium#1815] opened 2022-10-14 16:26 UTC
# Description

When opening a zipped Bruker folder, the sample names are not loaded correctly. Instead of the actual sample name, a string of numbers and letters is displayed that appears to be random (changes when reloading the file). The problem does not occur when opening `.nmrium` files and it also did not occur in earlier NMRium versions (it definitely worked in v0.27).  

# Reproduction

When the attached zipped Bruker is opened, random number and letter strings are displayed instead of the sample name. Tested in NMRium v0.32 and the development version.

Screenshot of displayed random sample names:

<img width="560" alt="Screenshot 2022-10-14 at 18 23 32" src="https://user-images.githubusercontent.com/41544471/195894775-16ef02c2-a70d-4c09-bf78-84e8387d7310.png">

[JSC-AE-12-8.zip](https://github.com/cheminfo/nmrium/files/9788204/JSC-AE-12-8.zip)

I am happy to provide additional information if that may be helpful and thanks a lot for your work on NMRium, I enjoy using it a lot!

**Comment by hamed-musallam** [comment] 2022-10-14 19:39
related to #1813

**Comment by jobo322** [comment] 2022-10-15 07:21
@jschneidewind, thanks for the advice, there is a fix in progress, could you test it in the next link, and is it possible to give us some feedback

https://deploy-preview-1817--nmrium.netlify.app/

**Comment by jschneidewind** [comment] 2022-10-15 14:35
Thanks a lot for your fast reply! Loading the sample names for zipped Bruker folders works in the deploy preview. 

Just a note regarding the current behaviour: sample names are now displayed together with the name of the subdirectory for the respective spectrum (e.g. the spectrum in subdirectory `10` of sample `JSC-AE-12-8` is displayed as `JSC-AE-12-8/10`). 

I think this is a good change, just wanted to highlight it since this behaviour differs from the previous one.

**Comment by lpatiny** [comment] 2022-10-15 14:56
duplicate of https://github.com/cheminfo/nmrium/issues/1813

**Closed by lpatiny** 2022-10-15 14:56 UTC
