### ISSUE TITLE
zones is not updated with shift X or Y axis

### ISSUE THREAD

**Issue by jobo322** [cheminfo/nmrium#2740] opened 2023-11-07 16:54 UTC
![zonesAreNotUpdated](https://github.com/cheminfo/nmrium/assets/12143935/e3493c20-5b0d-489a-9c1b-3150dfc14139)

**Comment by lpatiny** [comment] 2023-11-08 17:02
This is related to https://github.com/cheminfo/nmrium/issues/2661.

**Comment by jobo322** [comment] 2023-11-08 18:43
I solve it by 
- https://github.com/cheminfo/nmrium/pull/2744/commits/ae92541b149b6219ac0e8f09702cbb96917f0080

@hamed-musallam  is it correct or I am broking something else.

**Comment by jobo322** [comment] 2023-11-08 18:44
seems to me than when you call the contours it already are shifted

**Comment by hamed-musallam** [comment] 2023-11-09 06:54
> seems to me than when you call the contours it already are shifted

it works well, although the cause of its functionality differs from what you mentioned. The shift in the x and y filters alters the minimum and maximum values for both x and y, leading to changes in the domain. Consequently, this adjustment affects the scale function, ensuring that the contours are plotted in the correct position, accounting for the shifted values.

**Comment by hamed-musallam** [comment] 2023-11-10 08:06
fixed with https://github.com/cheminfo/nmrium/pull/2744

**Closed by hamed-musallam** 2023-11-10 08:06 UTC
