### ISSUE TITLE
Entering numbers causes spectrum switch

### ISSUE THREAD

**Issue by michaelwenk** [cheminfo/nmrium#1538] opened 2022-05-07 07:58 UTC
@lpatiny @hamed-musallam 
If we want to enter a sum for ranges it happens that the application switches to another spectrum when entering a certain value, e.g. 1. The same is for changing the number of equivalences in summary panel.

In case of ranges sum I can not change the value within the current selected spectrum. Instead it changes the sum value in the spectrum to which it was switching.

I attached two videos for demonstration:

https://user-images.githubusercontent.com/30418272/167244863-ebae39ed-5ecc-4026-8a84-825e7b2ec9b6.mov

https://user-images.githubusercontent.com/30418272/167244871-b053df98-d627-40a9-b073-e67cc50787c2.mov

**Comment by targos** [comment] 2022-05-07 11:41
Duplicate of https://github.com/cheminfo/nmrium/issues/1516. Fixed on master.

**Closed by targos** 2022-05-07 11:41 UTC
